import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header/main-header";
import AuthProvider from "@/context/AuthProvider";

import { getServerSession } from "next-auth/next";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({ children }) {



  return (
    <html lang="en">
      <body id="body" className={inter.className}>
        <AuthProvider> 
          <MainHeader />
          <div>
            {children}
          </div>
        </AuthProvider>
        </body>
    </html>
  );
}
